name: Codestyle

on:
  push:
    branches:
      - "*"
    paths:
    - '**.php'
  pull_request:
    branches:
      - "*"
    paths:
    - '**.php'

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [7.3]

    name: P${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS for the codestyle
        run: vendor/bin/phpcs
