name: phpunit
on: [push, pull_request]
jobs:
  run-phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ 5.3, 5.4, 5.5, 5.6, 7.1, 7.2, 7.3, 7.4 ]
        prefer: [ prefer-lowest, prefer-stable ]
    name: PHP ${{ matrix.php-versions }} ${{ matrix.prefer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.prefer }}-
          restore-keys: ${{ runner.os }}-composer-${{ matrix.prefer }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
          fail-fast: true

      - name: Install dependencies
        run: composer install --prefer-dist ${{ matrix.prefer }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --colors
